#!/bin/bash

# source /home/dev/.nvm/versions/node/v16.15.1/bin/node
# source ~/.nvm/nvm.sh

# ls -al ~/dev/
# /mnt/c/Users/haque/AppData/Roaming/npm -v

declare -A COLOURS
COLOURS[SET]='\033[0m'
COLOURS[DARKGRAY]='\033[1;30m'
COLOURS[RED]='\033[0;31m'
COLOURS[WHITE]='\033[1;37m'
COLOURS[GREEN]='\033[0;32m'
COLOURS[YELLOW]='\033[1;33m'
COLOURS[PURPLE]='\033[0;35m'

if [[ "$(tty)" != "Running on terminal" ]];then
    UI=false
fi

function echoColour() {
  [[ "${UI}" == "true" ]] && return

  if [ "${COLOURS[${1}]}" ]; then
    echo -e "${COLOURS[${1}]}$2${COLOURS[SET]}"
  else
    echoColour WHITE "${1}"
  fi
}

function echoColourTime() {
  [[ "${UI}" == "true" ]] && return

  if [ "${COLOURS[${1}]}" ]; then
    echo -e "${COLOURS['DARKGRAY']}$(date '+%Y-%m-%d %H:%M:%S')${COLOURS[SET]}: ${COLOURS[${1}]}$2${COLOURS[SET]}"
  else
    echoColourTime WHITE "${1}"
  fi
}

function is_root_user {
  echo $EUID
    [ "$EUID" -eq 0 ] && return 0

    echoColourTime RED "please run as sudo"
    return 1
}

function is_directory {
  if [ ! -d $1 ]; then
    echoColourTime RED "Directory does not exist - searched $1"

    return 1
  fi

  return 0
}

function use_existing_directory_question {
    local DIR=$1
    echoColour YELLOW "${DIR} directory already exists! Use this existing directory? (y/n)"
    read USE_EXISTING_DIR </dev/tty

    case ${USE_EXISTING_DIR} in
          y|Y|yes)
              is_directory_empty $DIR

              [[ $? -ne 0 ]] && echoColour RED "Directory ${DEFAULT_DIR} is not empty. Select an empty directory and re run script" && return 1

              echoColourTime GREEN "$DIR set for velox"

          return 0
          ;;
          n|No|N)
              echoColourTime GREEN "Cancelling. Please re run script and  select an empty directory.."
              return 1
          ;;
          * )
              echoColourTime RED "invalid option please enter y/Y, n|N"
              return 1
          ;;
      esac
}

DEFAULT_DIR="/home/${USER}/velox"
VELOX_DIR=''
TOKEN=''
function check_or_create_velox_directory {

  echoColour WHITE "Enter directory to create velox folder (leave blank to create in ${DEFAULT_DIR})?! "

  read directoryAnswer </dev/tty

  if [ -z "$directoryAnswer" ]; then
    echoColourTime "checking if directory ${DEFAULT_DIR} exists"
    is_directory "${DEFAULT_DIR}"

    if [ $? -eq 1 ]; then
      echoColour YELLOW "creating directory at ${DEFAULT_DIR}"
      mkdir -p "$DEFAULT_DIR"
      [ $? -ne 0 ] && echoColourTime RED "Failed to create ${DEFAULT_DIR}" && return 1

      return 0
    fi

     use_existing_directory_question $DEFAULT_DIR
    [ $? -ne 0 ] && return 1

    return 0
  fi

  ## User at this point has entered a directory. Check if the entered directory is a directory
  if [ ! -d $directoryAnswer ]; then
    echoColour RED "$directoryAnswer is not a directory";

    create_a_dir_question $directoryAnswer
    [ $? -ne 0 ] && return 1
  fi

  is_directory_empty $directoryAnswer

  [[ $? -ne 0 ]] && return 1
  VELOX_DIR=$directoryAnswer
  echoColourTime GREEN "set $VELOX_DIR as Velox dir"
}

# function check_ssh_key {

# }

function clone_velox_repo {
  echoColourTime DARKGRAY "Attempting to clone velox repo into $VELOX_DIR"
  # ls -al /home/$SUDO_USER/.ssh
  (GIT_SSH_COMMAND="ssh -o IdentitiesOnly=yes -i/home/${USER}/.ssh/id_rsa -F /dev/null" git clone git@ssh.dev.azure.com:v3/etechtfs/fsociety/velox $VELOX_DIR)

}

function is_directory_empty {
  [[ $# -eq 0 ]] && echoColourTime RED 'no args passed is_directory_empty' && return 1
  local REAL_PATH=$(realpath -- $1)

  echoColour DARKGRAY "checking if $1 directory is empty.."

  is_directory $REAL_PATH

  [ $? -ne 0 ] && return 1

  DIRECTORY_ITEMS_COUNT=$(ls -A ${REAL_PATH} | wc -l)
  [[ $DIRECTORY_ITEMS_COUNT -eq 0 ]] && return 0

  echoColourTime RED "${REAL_PATH} is not empty" && return 1
}

function install {
      [[ $# -eq 0 ]] && echoColourTime RED 'no args passed to is_bare_git' && return 1
      ls package.json 2>/dev/null
      [ $? -ne 0 ] && echoColour RED "no package.json file in ${1}. continuing ..." && return 2
      if [ -f ./package-lock.json ]; then
        rm package-lock.json
      fi
      update_npmrc
      npm install --legacy-peer-deps

      revert_npmrc
      [ $? -ne 0 ] && echoColour RED "${dir_array[$dirIndex]} npm failed" && return 2
}

function run_npm_install {
   npm --version
  (
    cd $VELOX_DIR
    local real=$(realpath -- ./)
    echo $real
    echoColourTime DARKGRAY "running npm install in each service"
    IFS=$'\n' read -r -d '' -a dir_array < <(find $real -maxdepth 1 -type d)

    for ((dirIndex=0; dirIndex < ${#dir_array[@]}; dirIndex++)); do
      cd ${dir_array[$dirIndex]}
      echo "-----------------------------"
      echo
      echoColour YELLOW "running install in service -- $(pwd)"

      if [ $(basename ${dir_array[$dirIndex]}) == "lib" ] && [ -d  "${dir_array[$dirIndex]}/core" ]; then
        (cd "${dir_array[$dirIndex]}/core"
        install ${dir_array[$dirIndex]})
      fi

      if [ $(basename ${dir_array[$dirIndex]}) == "lib" ] && [ -d  "${dir_array[$dirIndex]}/http" ]; then
        (cd "${dir_array[$dirIndex]}/core"
        install ${dir_array[$dirIndex]}
        )
      fi

      if [ $(basename ${dir_array[$dirIndex]}) != "lib" ]; then

        install ${dir_array[$dirIndex]}

        [ $? -eq 2 ] && continue

      fi





    done
  )
}

function update_npmrc {
  ls .npmrc 2>/dev/null
  if [ $? -eq 0 ]; then
    mv .npmrc .npmrc-back
    echo -e "@etech:registry=https://pkgs.dev.azure.com/etechtfs/_packaging/etech/npm/registry/\n//pkgs.dev.azure.com/etechtfs/_packaging/etech/npm/registry/:username=etech\n//pkgs.dev.azure.com/etechtfs/_packaging/etech/npm/registry/:_password=${TOKEN}\n//pkgs.dev.azure.com/etechtfs/_packaging/etech/npm/registry/:email=development@etech.net" > ./.npmrc
    # cat ./.npmrc
  fi
}

function revert_npmrc {
  # echo "revert"
  # ls -al
  ls .npmrc-back 2>/dev/null

    if [ $? -eq 0 ]; then
      rm .npmrc
      mv .npmrc-back  .npmrc
    fi
}


function is_git_repo {
  # $# is the count of args passed to this function
  [[ $# -eq 0 ]] && echoColourTime RED 'no args passed to is_bare_git' && return 1

  # check that the first arg passed to this function is a directory
  is_directory $1
  # $? checks the exit code of the is_directory function to verify its success. 0 is successful
  [ $? -gt 0 ] && return 1

  if [ $? -eq 0 ]; then
    # at this point we've verified that the arg ($1) is a directory
    # we now want to verify that the directory is a git repo.
    # Use subshell to cd into the directory so we stay in the current directory once the subshell command completes
    (cd $1 && [ -d .git ] && [[ 0 -eq "$(git rev-parse --is-inside-work-tree &>/dev/null && exit 0)" ]])
  fi
}

function check_required_variables {
  echoColour "please enter npm token"
read token </dev/tty

 [ -z "$token" ] && echoColour RED "Failed to enter npm token" && return 1

  TOKEN=$token
}

function create_a_dir_question {
  [ $# -eq 0 ] ||  [ -z $1 ] && echoColour RED "no args passed to create a dir question" && return 1
  [ -z $1 ] && echoColour RED "empty string passed" && return 1

  FULL_PATH=$(realpath -- $1)

  echoColour YELLOW "Create a directory at ${FULL_PATH}? (y/n)"

  read CREATE_DIR </dev/tty

  if [[ $CREATE_DIR == @(y|Y) ]] ; then
    mkdir $FULL_PATH

    [ $? -ne 0 ] && echoColour RED "failed to create dir ${FULL_PATH}" && return 1

    echoColour "Created directory $FULL_PATH"
  fi

 return 0
}

function run {
  # is_root_user



  [ $? -ne 0 ] && return
  check_required_variables

  [ $? -ne 0 ] && return

  check_or_create_velox_directory

  [ $? -ne 0 ] && return 1

  clone_velox_repo

  [ $? -ne 0 ] && return 1

  run_npm_install

  [ $? -ne 0 ] && return 1

  echo "NPM_VSTS_TOKEN=${TOKEN}" > .env



  # case ${directoryAnswer} in
  #      )
  #     ;;
  #     * )
  #         echoColourTime DARKGRAY "..creating velox directory in $Home/dev/"
  #     ;;
  # esac

  return 0
}

run


